# Generated by Django 5.2.8 on 2025-12-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='is_child_sponsor',
            field=models.BooleanField(default=False, verbose_name='Child Sponsorship'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='is_financial_supporter',
            field=models.BooleanField(default=False, verbose_name='Financial Support'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='Mentorship'),
        ),
    ]
